version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8046:80'
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    image: "reactapp"
    ports:
      - 4473:4473
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: "express"
    ports:
      - 3578:3578